### ISSUE TITLE
Typo of "Ability" in "Add Ability" modal

### ISSUE THREAD

**Issue by exonian** [PeteAUK/warscroll-designer#16]
**Describe the bug**
Modal title says "Abilitiy" and the first field placeholder says "Abilitiy Name" :)

![image](https://github.com/PeteAUK/warscroll-designer/assets/1237986/04f5df6c-0072-486c-bcfe-07f8dcd29964)

**Comment by PeteAUK** [comment]
My bad, should be fixed shortly.
