### ISSUE TITLE
Flavour Text, Grand Alliance, and Points not showing up on Finished WarScroll

### ISSUE THREAD

**Issue by DanielJPatterson** [PeteAUK/warscroll-designer#18]
**Describe the bug**
I created the attached Warscroll with your awesome tool, filling out the Flavour Text, Grand Alliance, and Points fields but these fields do not show up on the finished WarScroll.

**To Reproduce**
Create a Warscroll with these fields and hit the image button.

**Expected behaviour**
I expected these fields to be visible on the created Warscroll like Wahapedia:
https://wahapedia.ru/aos3/factions/slaves-to-darkness/Archaon-the-Everchosen

**Screenshots**
![Kholek Suneater Custom Warscroll](https://github.com/PeteAUK/warscroll-designer/assets/63020520/020e1a50-f8cf-4ab2-bd50-b7acbc6e6015)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by PeteAUK** [comment]
Morning!  I believe these things should now all be resolved :)

The flavour text was a weird CSS issue - the text was there, just not showing, very weird!

Grand Alliance now correctly prepends onto the Keywords section.  Am sure this was working, but clearly stopped somewhere along the way.

Points was one field I'd only put the entry box in for as my focus was replicating the existing warscroll layout.  However I've now hooked this up and it displays in the top right of the header.  Please let me know if that works or is a hinderance.  Longer term the intention is to add a Pitched Battle Profile at the bottom, but that requires additional fields being added such as behemoth, leader, battleline etc.

As an aside, on your warscroll have you tried putting "Herald of the Tempest" into the "Unit Subtype" field?

**Comment by exonian** [comment]
These don't seem to be fixed for me. I've tried forced refresh, disabling the cache etc but I'm not seeing these things on my warscroll.
`stylesheet.css?b=2` and `aos-v3.css?b=2` in case that's useful info at all

**Comment by PeteAUK** [comment]
Hmm, it appears that I may have not committed that change 🤦‍♂️  I'll try and sort that one out when I get home this evening

**Comment by exonian** [comment]
Yep that's sorted it now (and the cache buster was effective)

**Comment by PeteAUK** [comment]
Marvellous.  Sorry about that - clearly I'd got ahead of myself!

Sadly cache busting seems to be the only way to reliably ensure Chrome doesn't "kindly" keep hold of old versions
