### ISSUE TITLE
Save and share created warscrolls.

### ISSUE THREAD

**Issue by Sunblastlaser** [PeteAUK/warscroll-designer#21]
A clear and concise description of what the problem is. e.g.. I'm always frustrated when ...
It would be useful to be able to save the full warscroll as a published version- pdf?, also to make it so that it doesn’t include an ellipsis where a rule is too long.

**Comment by PeteAUK** [comment]
Hi, are you changing the page size of the warscroll?  If you click on the triple cog icon you can increase the page size to allow longer box sizes, right the way up to a full height A4 page

![image](https://github.com/PeteAUK/warscroll-designer/assets/893132/f0d3a775-8683-4fe2-86ed-05a2deae994f)


![image](https://github.com/PeteAUK/warscroll-designer/assets/893132/3a810cfc-853c-46e4-91d3-22e381a53ab5)

**Comment by Sunblastlaser** [comment]
Thank you for the help :)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
