### ISSUE TITLE
Unable to load local files saved prior to updates

### ISSUE THREAD

**Issue by Mystic-Fox** [PeteAUK/warscroll-designer#9]
**Describe the bug**
After the new updated design of the site, I'm unable to load my old custom warscrolls which I saved locally.

**To Reproduce**
1: Have an old locally saved warscroll.
2: Open the left hand info panel, where it should be displayed.
3: Click on the saved file, observe nothing happening to the main body of the site.

**Expected behaviour**
The saved file should populate the custom warscroll, presumably.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 112.0

**Comment by PeteAUK** [comment]
I think I know what this might be - leave it with me and I'll sort out a solution

**Comment by Mystic-Fox** [comment]
Leave it with you as in leave the files with you? If so where do I find the files?

**Comment by PeteAUK** [comment]
Just the problem :)  I have this on the radar to fix over the weekend

**Comment by Mystic-Fox** [comment]
Alright, thanks for the hard work! Love the site

**Comment by PeteAUK** [comment]
I believe this should now be fixed.

**Comment by Mystic-Fox** [comment]
It is not. The local file loads only the title as 'Test2' and doesn't fill any other fields.

**Comment by PeteAUK** [comment]
Really sorry about that, I left a piece of test code that I used to get it to work.  I've a horrible feeling this also may have overwritten the local warscroll too 😬  I've removed the test code which should make your other old warscrolls load now.

**Comment by Mystic-Fox** [comment]
Unfortunately it has overwritten a couple of them, but it's nothing I can't fix. Luckily I saved some jpgs of the old ones I was testing with just in case something like this happened. So I can copy off those! Thanks a bunch for your help

**Comment by PeteAUK** [comment]
Apologies on that again, but glad we've got this one sorted out :)
